[package]
name = "cad_gtm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/cgtm_geomerty",
    "crates/cgtm_topology"
]

[dependencies]
